Repository jenkins-x/jx-cli, pull requests merged in 2020-11, with the labels that each got.

#579 fix: add dashboard and ui commands
  docs/cmd/jx.md
  docs/cmd/jx_create.md
  docs/cmd/jx_create_project.md
  docs/cmd/jx_create_pullrequest.md
  docs/cmd/jx_create_quickstart.md
  docs/cmd/jx_dashboard.md
  docs/cmd/jx_get.md
  docs/cmd/jx_get_activities.md
  docs/cmd/jx_get_application.md
  docs/cmd/jx_get_build.md
  docs/cmd/jx_get_build_logs.md
  docs/cmd/jx_get_build_pods.md
  docs/cmd/jx_get_pipelines.md
  docs/cmd/jx_get_previews.md
  docs/cmd/jx_import.md
  docs/cmd/jx_namespace.md
  docs/cmd/jx_start.md
  docs/cmd/jx_start_pipeline.md
  docs/cmd/jx_stop.md
  docs/cmd/jx_stop_pipeline.md
  docs/cmd/jx_ui.md
  docs/cmd/jx_upgrade.md
  docs/cmd/jx_upgrade_cli.md
  docs/cmd/jx_upgrade_plugins.md
  docs/cmd/jx_version.md
  docs/man/man1/jx-dashboard.1
  docs/man/man1/jx-ui.1
  docs/man/man1/jx.1
  go.mod
  go.sum
  pkg/cmd/dashboard/dashboard.go
  pkg/cmd/root.go
  pkg/cmd/ui/ui.go
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
  pkg/plugins/versions.go
Labels: approved, size/XL

#595 fix: create multi-arch images
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
  Dockerfile-boot
  README.md
  build.sh
  cloudbuild.yaml
  pkg/cmd/upgrade/upgrade_plugins.go
Labels: approved, size/XL

#620 fix: improve multi arch build
  .jx/updatebot.yaml
  .lighthouse/jenkins-x/release.yaml
  Dockerfile-boot
  cloudbuild.yaml
  go.mod
  go.sum
Labels: approved, size/M

#632 fix: lets not use a custom user
  Dockerfile-boot
  go.mod
  go.sum
Labels: approved, size/S

#640 docs: edit Contributing guide
  CONTRIBUTING.MD
Labels: size/S

#641 fix: lets fail if you change to a namespace that doesn't exist
  go.mod
  go.sum
  pkg/cmd/namespace/namespace.go
Labels: approved, size/L

#638 golang version was out of date. 1.15.5 is supported.
  CONTRIBUTING.MD
Labels: needs-ok-to-test, size/XS
