Repository jenkins-x/jx-cli, pull requests merged in 2020-12, with the labels that each got.

#666 fix: upgrade to latest jx-api
  go.mod
  go.sum
  pkg/cmd/namespace/namespace.go
  pkg/cmd/root.go
  pkg/cmd/ui/ui.go
  pkg/cmd/upgrade/upgrade_cli.go
  pkg/plugins/helpers.go
  pkg/plugins/versions.go
Labels: approved, size/M

#678 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/M, updatebot

#682 fix: allow easy install of jenkins-x-plugins
  go.mod
  go.sum
  pkg/cmd/root.go
Labels: approved, size/M

#696 feat: handle upgrading CLI from a versionstream in a Kptfile
  go.mod
  go.sum
  pkg/cmd/upgrade/upgrade_cli.go
Labels: approved, size/L

#717 feat: pass arguments to octant binary from jx ui
  docs/cmd/jx.md
  docs/cmd/jx_create.md
  docs/cmd/jx_create_project.md
  docs/cmd/jx_create_pullrequest.md
  docs/cmd/jx_create_quickstart.md
  docs/cmd/jx_dashboard.md
  docs/cmd/jx_get.md
  docs/cmd/jx_get_activities.md
  docs/cmd/jx_get_application.md
  docs/cmd/jx_get_build.md
  docs/cmd/jx_get_build_logs.md
  docs/cmd/jx_get_build_pods.md
  docs/cmd/jx_get_pipelines.md
  docs/cmd/jx_get_previews.md
  docs/cmd/jx_import.md
  docs/cmd/jx_namespace.md
  docs/cmd/jx_start.md
  docs/cmd/jx_start_pipeline.md
  docs/cmd/jx_stop.md
  docs/cmd/jx_stop_pipeline.md
  docs/cmd/jx_ui.md
  docs/cmd/jx_upgrade.md
  docs/cmd/jx_upgrade_cli.md
  docs/cmd/jx_upgrade_plugins.md
  docs/cmd/jx_version.md
  docs/man/man1/jx-ui.1
  docs/man/man1/jx-upgrade-cli.1
  docs/man/man1/jx-upgrade-plugins.1
  pkg/cmd/ui/ui.go
Labels: approved, lgtm, ok-to-test, size/M

#729 chore: upgrade preview and promote plugins
  pkg/plugins/versions.go
Labels: approved, size/XS

#751 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S
