Repository jenkins-x/jx-cli, pull requests merged in 2020-08, with the labels that each got.

#133 docs: fix issue with preview link
  README.md
Labels: approved, lgtm, size/XS

#169 chore: switch from labs to jenkinsxio registry
  Makefile
  jenkins-x.yml
Labels: approved, size/S

#172 fix: add jx-jenkins plugin
  Dockerfile
  README.md
  pkg/plugins/versions.go
Labels: approved, size/S

#175 fix: switch pipeline from private image
  jenkins-x.yml
Labels: approved, size/XS

#180 fix: better promote PR
  promote/main.go
Labels: approved, size/XS

#200 fix: ignore optional plugins in the image
  Dockerfile
  jenkins-x.yml
  pkg/cmd/upgrade/upgrade.go
  promote/main.go
Labels: approved, size/S

#203 fix: lets always use the right plugin version
  Dockerfile
  pkg/cmd/root.go
Labels: approved, size/M

#212 fix: ugprade secret
  pkg/plugins/versions.go
  promote.sh
Labels: approved, size/S
