Repository jenkins-x/jx-cli, pull requests merged in 2020-09, with the labels that each got.

#229 fix: increase resources
  jenkins-x.yml
Labels: approved, size/S

#241 refactor: remove duplicated version ldflags
  .goreleaser.yml
  Makefile
Labels: approved, lgtm, size/XS

#242 fix: fix issue with missing version info in binary
  .goreleaser.yml
Labels: approved, lgtm, size/XS

#278 fix: avoid errors if no clusterName
  pkg/cmd/root.go
Labels: approved, size/XS

#284 feat: add upgrade cli command
  go.mod
  go.sum
  pkg/cmd/upgrade/upgrade.go
  pkg/cmd/upgrade/upgrade_cli.go
  pkg/cmd/upgrade/upgrade_cli_test.go
  pkg/cmd/upgrade/upgrade_plugins.go
  pkg/cmd/upgrade/upgrade_plugins_test.go
Labels: approved, size/XXL

#286 fix: add nicer namespace switcher
  README.md
  cmd/app/main.go
  docs/cmd/jx.md
  docs/cmd/jx_create.md
  docs/cmd/jx_create_project.md
  docs/cmd/jx_create_pullrequest.md
  docs/cmd/jx_create_quickstart.md
  docs/cmd/jx_get.md
  docs/cmd/jx_get_activities.md
  docs/cmd/jx_get_application.md
  docs/cmd/jx_get_build.md
  docs/cmd/jx_get_build_logs.md
  docs/cmd/jx_get_build_pods.md
  docs/cmd/jx_get_pipelines.md
  docs/cmd/jx_get_previews.md
  docs/cmd/jx_import.md
  docs/cmd/jx_namespace.md
  docs/cmd/jx_start.md
  docs/cmd/jx_start_pipeline.md
  docs/cmd/jx_stop.md
  docs/cmd/jx_stop_pipeline.md
  docs/cmd/jx_upgrade.md
  docs/cmd/jx_upgrade_cli.md
  docs/cmd/jx_upgrade_plugins.md
  docs/cmd/jx_version.md
  docs/man/man1/jx-create-project.1
  docs/man/man1/jx-create-pullrequest.1
  docs/man/man1/jx-create-quickstart.1
  docs/man/man1/jx-create.1
  docs/man/man1/jx-get-activities.1
  docs/man/man1/jx-get-application.1
  docs/man/man1/jx-get-build-logs.1
  docs/man/man1/jx-get-build-pods.1
  docs/man/man1/jx-get-build.1
  docs/man/man1/jx-get-pipelines.1
  docs/man/man1/jx-get-previews.1
  docs/man/man1/jx-get.1
  docs/man/man1/jx-import.1
  docs/man/man1/jx-namespace.1
  docs/man/man1/jx-start-pipeline.1
  docs/man/man1/jx-start.1
  docs/man/man1/jx-stop-pipeline.1
  docs/man/man1/jx-stop.1
  docs/man/man1/jx-upgrade-cli.1
  docs/man/man1/jx-upgrade-plugins.1
  docs/man/man1/jx-upgrade.1
  docs/man/man1/jx-version.1
  docs/man/man1/jx.1
  jenkins-x.yml
  pkg/cmd/namespace/namespace.go
  pkg/cmd/root.go
  pkg/cmd/upgrade/upgrade_cli_test.go
  promote/main.go
Labels: approved, size/XXL

#293 fix: for switching ns inside a pod
  jenkins-x.yml
  pkg/cmd/namespace/namespace.go
Labels: approved, size/S

#314 fix: upgrade dependencies
  go.mod
  go.sum
Labels: approved, size/M

#359 feat: add a generic chart that different style pods can execute jx-cl…
  charts/jx-cli/.helmignore
  charts/jx-cli/Chart.yaml
  charts/jx-cli/Makefile
  charts/jx-cli/templates/NOTES.txt
  charts/jx-cli/templates/_helpers.tpl
  charts/jx-cli/templates/clusterrole.yaml
  charts/jx-cli/templates/clusterrolebinding.yaml
  charts/jx-cli/templates/cronjob.yaml
  charts/jx-cli/templates/daemonset.yaml
  charts/jx-cli/templates/deployment.yaml
  charts/jx-cli/templates/job.yaml
  charts/jx-cli/templates/role.yaml
  charts/jx-cli/templates/rolebinding.yaml
  charts/jx-cli/templates/service.yaml
  charts/jx-cli/templates/serviceaccount.yaml
  charts/jx-cli/values.yaml
  jenkins-x.yml
Labels: approved, size/XL

#360 chore: lets make sure we always use the full name for these generic c…
  charts/jx-cli/templates/_helpers.tpl
  charts/jx-cli/templates/clusterrole.yaml
  charts/jx-cli/templates/clusterrolebinding.yaml
  charts/jx-cli/templates/cronjob.yaml
  charts/jx-cli/templates/daemonset.yaml
  charts/jx-cli/templates/deployment.yaml
  charts/jx-cli/templates/job.yaml
  charts/jx-cli/templates/role.yaml
  charts/jx-cli/templates/rolebinding.yaml
  charts/jx-cli/templates/service.yaml
  charts/jx-cli/templates/serviceaccount.yaml
Labels: approved, size/M

#391 chore: promote the jx-cli helm chart in the version stream
  promote/main.go
Labels: approved, size/XS

#398 fix: switch to jx-updatebot
  .jx/updatebot.yaml
  Makefile
  go.mod
  go.sum
  jenkins-x.yml
  promote.sh
  promote/.gitignore
  promote/go.mod
  promote/go.sum
  promote/main.go
Labels: approved, size/XXL
