Repository jenkins-x/jx-cli, pull requests merged in 2021-03, with the labels that each got.

#1083 fix: include health in the boot image
  go.mod
  go.sum
  pkg/cmd/upgrade/upgrade_plugins.go
Labels: approved, size/XS

#1091 fix: add alias for the old add app command
  pkg/cmd/root.go
Labels: approved, size/S

#1109 chore: enable multi platform tests for validating plugin mechanism
  .github/workflows/plugins.yaml
  go.mod
  go.sum
  pkg/cmd/root.go
Labels: approved, size/M

#1111 fix: GHA trigger on PR
  .github/workflows/plugins-pr.yaml
Labels: approved, size/XS

#1115 fix: add yq binary
  Dockerfile-boot
  go.mod
  go.sum
Labels: approved, size/S

#1116 fix: add yq to the terraform images
  Dockerfile-boot
  Dockerfile-tfo-aws
  Dockerfile-tfo-gcp
Labels: approved, size/S

#1117 fix: use correct yq URL
  Dockerfile-boot
  Dockerfile-tfo-aws
  Dockerfile-tfo-gcp
Labels: approved, size/XS

#1147 fix: upgrade octant
  go.mod
  go.sum
  pkg/plugins/versions.go
Labels: approved, size/S
